/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-114629-g1590a96adc-20240403"
#endif /* AVUTIL_FFVERSION_H */
